export const suroviny = [
  "Ananas",
  "Angrešt",
  "Arašídy",
  "Artyčoky",
  "Avokádo",
  "Banány",
  "Bazalka",
  "Brambory",
  "Brokolice",
  "Bulgur",
  "Celer",
  "Cibule",
  "Cizrna",
  "Cuketa",
  "Cukr",
  "Čaj",
  "Červená řepa",
  "Česnek",
  "Čočka",
  "Čokoláda",
  "Datle",
  "Droždí",
  "Dýně",
  "Eidam",
  "Estragon",
  "Fazole",
  "Fenykl",
  "Fíky",
  "Flank steak",
  "Grapefruit",
  "Granátové jablko",
  "Grilovací koření",
  "Hrášek",
  "Hřebíček",
  "Hrušky",
  "Hořčice",
  "Houby",
  "Chia semínka",
  "Chléb",
  "Chilli papričky",
  "Chřest",
  "Indické koření",
  "Instantní rýže",
  "Italské bylinky",
  "Jablka",
  "Jahody",
  "Javorový sirup",
  "Jarní cibulka",
  "Kachní maso",
  "Kapusta",
  "Křen",
  "Krevety",
  "Kuřecí maso",
  "Kuskus",
  "Lilek",
  "Limetka",
  "Listový špenát",
  "Losos",
  "Loupaná rajčata",
  "Mangold",
  "Mango",
  "Máslo",
  "Med",
  "Mrkev",
  "Mléko",
  "Mořské řasy",
  "Nakládané okurky",
  "Nektarinky",
  "Nutella",
  "Nudle",
  "Niva",
  "Olivový olej",
  "Oregano",
  "Okurky",
  "Ořechy",
  "Ovesné vločky",
  "Paprika",
  "Parmazán",
  "Pečivo",
  "Pórek",
  "Pstruh",
  "Prášek do pečiva",
  "Rajčata",
  "Rozinky",
  "Rukola",
  "Rybíz",
  "Rýže",
  "Ředkvičky",
  "Řapíkatý celer",
  "Řecký jogurt",
  "Salát",
  "Skořice",
  "Slanina",
  "Smetana",
  "Sýr",
  "Šalvěj",
  "Šalotka",
  "Šlehačka",
  "Špenát",
  "Špek",
  "Švestky",
  "Těstoviny",
  "Tofu",
  "Treska",
  "Tymián",
  "Tvaroh",
  "Uzené maso",
  "Uzená paprika",
  "Uzený losos",
  "Vanilka",
  "Vejce",
  "Vepřové maso",
  "Višně",
  "Voda",
  "Zázvor",
  "Zelené fazolky",
  "Zelí",
  "Zmrzlina",
  "Žampiony",
];

export const nazvy = [
  "Africký sumeček",
  "Albánský fazolový salát",
  "Aljašská treska",
  "Americká pečeně",
  "Americká pizza",
  "Andaluzské rizoto",
  "Arabská krůtí prsa",
  "Asijská pánev",
  "Avokádová pomazánka",
  "Bakoňské vepřové kotlety",
  "Balkánská studená polévka tarator",
  "Banánové vepřové maso",
  "Banánový dezert",
  "Barevná kapsa",
  "Barevná polévka",
  "Barevná rýže",
  "Barevná vřetena",
  "Barevné brambory",
  "Barevné maso",
  "Barevné těstoviny",
  "Barevné vepřové nudličky",
  "Barevné špagety",
  "Barevný kopečkový kuskus",
  "Baskické fazolky",
  "Bat salát z červené nebo černé čočky",
  "Batátová polévka krémová",
  "Beef shepherd´s pie - hovězí pastýřský koláč",
  "Beskydská polévka",
  "Beskydské šišky",
  "Bezmasá čína",
  "Bezé řezy",
  "Boeuf aux canneberges - hovězí maso na brusinkách",
  "Bostonské pečené fazole",
  "Bramboro-pohanková kaše",
  "Bramborovo-celerová kaše",
  "Bramborovo-celerové pyré",
  "Bramborovo-hrachová kaše",
  "Bramborovo-kapustová musaka",
  "Bramborovo-mrkvové pyré",
  "Bramborová kaše",
  "Bramborová kaše s pohankou",
  "Bramborová mléčná polévka",
  "Bramborová musaka",
  "Bramborová polévka",
  "Bramborová roláda",
  "Bramborové knedlíky",
  "Bramborové omelety se zelím",
  "Bramborové placky",
  "Bramborové pyré",
  "Bramborové suflé",
  "Bramborové šišky",
  "Bramborový guláš",
  "Bramborový knedlík",
  "Bramborový krém",
  "Bramborový nákyp",
  "Bramborový salát",
  "Bramborový závin plněný zeleninou",
  "Brambory",
  "Brambory opékané",
  "Brambory pečené",
  "Brambory vařené",
  "Brambory zapečené",
  "Bramborák",
  "Bratislavské vepřové plecko",
  "Brokolice",
  "Brokolicovo-kukuřičné placičky",
  "Brokolicová poezie",
  "Brokolicová polévka",
  "Brokolicové karbanátky",
  "Brokolicové krokety s hermelínem",
  "Brokolicové špagety",
  "Brokolicový krém",
  "Brokolicový nákyp",
  "Bryndzové halušky „liptovského baču“",
  "Bublanina piškotová",
  "Bublanina třená",
  "Bulgur",
  "Bulgur salát",
  "Bulgur se sušeným ovocem a zakysanou smetanou",
  "Bulgur se zeleninou ratatouille a tofu",
  "Bulgurové placičky s paprikou a sýrem",
  "Bulgurový salát",
  "Bulgurový salát s dýní a tofu",
  "Bulharská polévka",
  "Bulharská sarma",
  "Bulharské zelí s krůtím masem",
  "Bylinková tarhoňa se zeleným hráškem a cibulovými kroužky",
  "Bylinkové halušky",
  "Bílá káva",
  "Bílé fazole po florentinsku",
  "Bílé fazole s vepřovým masem a zelím",
  "Candát na rozmarýnu",
  "Candát na rozmarýnu s pomerančovou šťávou",
  "Candát s bulgurem a zeleninou",
  "Carpaccio z červené řepy a kozího sýru",
  "Celer zapečený s bramborami a sýrem",
  "Celer zapékaný",
  "Celero-šťouchané brambory",
  "Celerová polévka",
  "Celerová polévka krémová",
  "Celerová pomazánka",
  "Celerové karbanátky",
  "Celerový bramborák",
  "Celerový salát",
  "Celerový salát s dresinkem, pečivo",
  "Celerový salát s tuňákem a čerstvými rajčaty",
  "Celozrnné špecle s pečenými rajčaty a kukuřicí, bazalkový dresink",
  "Celozrnný knedlík",
  "Chalupářské rybí filety z aljašské tresky",
  "Chicken burrito",
  "Chlupatá rýže",
  "Chlupaté knedlíky",
  "Chléb s pomazánkovým máslem",
  "Chřest s holandskou omáčkou",
  "Chřestová polévka",
  "Chřestový salát s rajčaty a ředkvičkami",
  "Cibulová omáčka",
  "Cibulová polévka",
  "Cikánská hovězí pečeně",
  "Cikánská hovězí roláda",
  "Citronáda",
  "Citronáda s mátou",
  "Citrónová omáčka",
  "Cizrna na italský způsob",
  "Cizrna na paprice",
  "Cizrna na paprice s pórkem",
  "Cizrna na rajčatech",
  "Cizrna po indicku",
  "Cizrna se zeleninou a strouhaným šmakounem",
  "Cizrnová kaše",
  "Cizrnová polévka",
  "Cizrnová polévka s opraženou zeleninou",
  "Cizrnová polévka s červenými fazolemi",
  "Cizrnová polévka se smetanou",
  "Cizrnová pomazánka",
  "Cizrnová pomazánka s paprikou",
  "Cizrnová směs s dýní hokaido",
  "Cizrnové halušky",
  'Cizrnové palačinky s "nutelkou"',
  "Cizrnový burger s ananasovou salsou",
  "Cizrnový krém",
  "Cizrnový salát",
  "Cizrnový salát s kuskusem a zeleninou",
  "Cuketa plněná pohankou a sýrem",
  "Cuketová nádivka",
  "Cuketová polévka s opraženou houskou",
  "Cuketová polévka s červenou čočkou",
  "Cuketová pomazánka",
  "Cuketové hranolky z trouby",
  "Cuketové karbanátky s kukuřičnou strouhankou",
  "Cuketové krokety",
  "Cuketové rizoto",
  "Cuketový flamendr",
  "Cuketový koláč",
  "Cuketový kotlík",
  "Cuketový nákyp",
  "Cuketový prejt",
  "Cukeťák",
  "Císařovy brambory s kuřecím steakem",
  "Císařské brambory",
  "Debrecínský guláš",
  "Domažlické vepřové ragú",
  "Domácí buchty plněné mákem",
  "Domácí buchty plněné povidly, zavařeninou",
  "Domácí tvarohový krém",
  "Doudlebský skřivan s vepřovými játry",
  "Drožďová polévka",
  "Drožďová pomazánka",
  "Dršťková polévka z hlívy ústřičné",
  "Drůbeží jehla po srbsku",
  "Drůbeží játra",
  "Drůbeží játra na ananasu a jablkách",
  "Drůbeží játra na rajčatech",
  "Drůbeží játra na tymiánu s mandlemi",
  "Drůbeží játra s pórkem",
  "Drůbeží játra se žampiony",
  "Drůbeží kousky po srbsku",
  "Drůbeží řízek v brokolicovém těstíčku",
  "Drůbková polévka",
  "Drůbková polévka s těstovinou",
  "Dukátové buchtičky s krémem",
  "Dušená hlávková kapusta",
  "Dušená kapusta",
  "Dušená kyselá kapusta",
  "Dušená mrkev",
  "Dušená mrkev s hráškem",
  "Dušená míchaná zelenina",
  "Dušená rýže",
  "Dušená tarhoňa",
  "Dušená vepřová plec na sušených meruňkách",
  "Dušené fazolky",
  "Dušené hlávkové zelí",
  "Dušené kyselé zelí",
  "Dušené papriky",
  "Dušený hrášek",
  "Dušený kedluben",
  "Dušený květák",
  "Dušený květák po římsku",
  "Dušený pórek",
  "Dušený špenát",
  "Dvoubarevný tvarohový krém s čokoládovými lupínky",
  "Dýně smažená v těstíčku",
  "Dýňovo-mrkvový krém s čočkou",
  "Dýňová caponata",
  "Dýňová omáčka s parmazánem",
  "Dýňová omáčka s červenou paprikou",
  "Dýňová polévka",
  "Dýňová polévka s bílým jogurtem",
  "Dýňová polévka s popcornem",
  "Dýňová polévka s pórkem a ovesnými vločkami",
  "Dýňová polévka se sladkou bramborou",
  "Dýňové muffinky s tvarohovým krémem",
  "Dýňové noky v sýrové omáčce",
  "Dýňové rizoto",
  "Dýňové rizoto s mascarpone",
  "Dýňový halloweenský moučník",
  "Dýňový krém",
  "Dýňový krém se špenátovým svítkem",
  "Dřevorubecké brambory s houbami",
  "Džusy",
  "Džuveč",
  "Džuveč z králíka",
  "Falafel - smažené hrachové kuličky",
  "Fazole na kyselo",
  "Fazole plaki",
  "Fazole s kořenovou zeleninou v rajské omáčce",
  "Fazolkové špagety",
  "Fazolky s masem zapékané",
  "Fazolky zadělávané",
  "Fazolovo-zeleninový salát s balkánským sýrem",
  "Fazolová jarní polévka",
  "Fazolová krémová polévka",
  "Fazolová mléčná",
  "Fazolová polévka",
  "Fazolová polévka s kysaným zelím",
  "Fazolová pánev",
  "Fazolové chilli",
  "Fazolové lusky",
  "Fazolové ragú",
  "Fazolový guláš",
  "Fazolový krém",
  "Fazolový salát",
  "Fenyklový salát s pomerančem",
  "Filet tilápie v sýrovo-limetkové kůrce",
  "Filety z aljašské tresky florián",
  "Filety ze sumečka afrického ve strouhance z bílého chleba",
  "Filé po kanadsku s brusinkovou omáčkou",
  "Fish pie - anglický rybí nákyp",
  "Francouzské brambory",
  "Frankfurtská polévka zeleninová",
  "Frankfurtský závitek",
  "Gnocchi s grilovanou zeleninou a parmazánem",
  "Gnocchi se smetanovým špenátem",
  "Gnocchi v rajčatové omáčce",
  "Granko",
  "Gratinované brambory s krémovým špenátem a parmezánem",
  "Gratinovaný losos s listovým špenátem a těstovinami",
  "Gravče-tavče s pórkem",
  "Grilovaná cuketa s lilkem",
  "Grilovaná polenta, mladý špenát",
  "Grilovaná zelenina s dresinkem",
  "Grilovaný filet z tilápie v bylinkovém pestě",
  "Grilovaný kuřecí steak špikovaný listovým špenátem",
  "Guláš z hlívy ústřičné",
  "Gulášová polévka",
  "Haluškové noky zapečené se špenátem a sýrem",
  "Halušky",
  "Halušky s cizrnou a bryndzou",
  "Halušky se žampiony a špenátem",
  "Hawajská rýže se šunkou a kokosem",
  "Haše",
  "Haše z telecího masa",
  "Hašé masové",
  "Hašé polévka",
  "Hašé z králíka",
  "Hašé z telecího masa",
  "Hejtmanský měšec",
  "Hlávkový salát",
  "Hlávkový salát s kyselým mlékem",
  "Hlávkový salát se slaninou",
  "Hlávkový salát se smetanou",
  "Hlíva ústřičná na smetaně s mrkví a jarní cibulkou",
  "Hlíva ústřičná v křenové omáčce",
  "Holandské vepřové plátky",
  "Holandský řízek",
  "Houbová pohanka",
  "Houbové halušky",
  "Houbové italské rizoto",
  "Houbové rizoto",
  "Houbový bulgur",
  "Houbový guláš s červenou fazolí",
  "Houbový kuba s tarhoňou",
  "Houbový pekáček",
  "Houskové knedlíky (kynuté)",
  "Houskové knedlíky (s kypřicím práškem do pečiva)",
  "Houskový knedlík s čirokovou moukou",
  'Hovězí "riccota"',
  "Hovězí dušené v mrkvi",
  "Hovězí dušené v zelenině",
  "Hovězí guláš",
  "Hovězí kostky na paprice s houbami",
  "Hovězí krk na houbách",
  "Hovězí maso na cibuli",
  "Hovězí maso po budějovicku",
  "Hovězí maso s paprikami a ananasem",
  "Hovězí maso se zeleninou a cizrnou",
  "Hovězí maso vařené",
  "Hovězí na celeru",
  "Hovězí na smetaně",
  "Hovězí na zahradnický způsob",
  "Hovězí na žampiónech",
  "Hovězí pečeně cikánská",
  "Hovězí pečeně frankfurtská",
  "Hovězí pečeně na celeru",
  "Hovězí pečeně na houbách",
  "Hovězí pečeně na paprice",
  "Hovězí pečeně na paprikách",
  "Hovězí pečeně na rajčatech",
  "Hovězí pečeně na zelenině",
  "Hovězí pečeně na česneku",
  "Hovězí pečeně na žampiónech",
  "Hovězí pečeně pražská",
  "Hovězí pečeně protýkaná zeleninou",
  "Hovězí pečeně přírodní",
  "Hovězí pečeně ruská",
  "Hovězí pečeně se šunkou",
  "Hovězí pečeně znojemská",
  "Hovězí pečeně štěpánská",
  "Hovězí plátek (roštěná) na houbách",
  "Hovězí plátek (roštěná) na slanině",
  "Hovězí plátek (roštěná) na žampiónech",
  "Hovězí plátek (roštěná) přírodní",
  "Hovězí plátek (roštěná) znojemská",
  "Hovězí plátek bratislavský",
  "Hovězí plátek se šípkovou omáčkou",
  "Hovězí plátky na kmíně",
  "Hovězí plátky na pražský způsob",
  "Hovězí plátky s rajčatovým protlakem",
  "Hovězí po provensálsku",
  "Hovězí polévka s játrovou rýží",
  "Hovězí polévka s krupicovými haluškami",
  "Hovězí polévka s majoránkovým kapáním",
  "Hovězí polévka s masovými knedlíčky",
  "Hovězí polévka s těstovinou",
  "Hovězí polévka s tříbarevnou vaječnou sedlinou",
  "Hovězí ragú",
  "Hovězí ragú se zeleninou a cizrnou",
  "Hovězí s cizrnou",
  "Hovězí svíčková po stroganovsku",
  "Hovězí tokáň",
  "Hovězí v kapustě",
  "Hovězí v kedlubnách",
  "Hovězí v mrkvi",
  "Hovězí v zelenině",
  "Hovězí vařené",
  "Hovězí vývar s celestýnskými nudlemi",
  "Hovězí vývar s petrželovým kapáním",
  "Hovězí závitek",
  "Hraběnčiny řezy",
  "Hrachová kaše",
  "Hrachová polévka",
  "Hrachová polévka s houstičkou",
  "Hrachová polévka s jarní cibulkou",
  "Hrachová pomazánka",
  "Hrachové karbanátky",
  "Hrachové placičky",
  "Hrnkový domácí perník na plech",
  "Hrstková polévka",
  "Hrstkový bulgur",
  "Hrách na kmíně",
  "Hrách po indicku",
  "Hrách po španělsku",
  "Hrášek dušený",
  "Hrášek přírodní",
  "Hrášková krémová polévka",
  "Hrášková polévka",
  "Hrášková polévka se zavářkou",
  "Hrášková pomazánka s bylinkami",
  "Hráškové pyré",
  "Hráškový krém",
  "Hráškový krém s bylinkovými krutonky",
  "Hráškový krém s krupicovými nočky se šunkou",
  "Husa pečená",
  "Hutná bramborová polévka (prívarok)",
  "Hutná fazolová polévka (prívarok)",
  "Hutná hrášková polévka (prívarok)",
  "Hutná mrkvová polévka (prívarok)",
  "Hutná tykvová polévka (prívarok)",
  "Hutná zeleninová polévka (prívarok)",
  "Indická polévka muligatawny",
  "Italská cizrnová polévka",
  "Italská pohanka",
  "Italská polévka",
  "Italská tomatová polévka s fazolemi a sýrem",
  "Italská zeleninová polévka (minestrone)",
  'Italské "caprese" – rajčata prokládaná mozzarellou',
  "Italské těstoviny se šunkou",
  "Italský guláš (zbruf se sýrem)",
  "Italský plátek na medu a tymiánu",
  "Ivetčina kašička",
  "Jablečno-medový nápoj",
  "Jablečná polévka",
  "Jablečné hrudky",
  "Jablečný koláč",
  "Jablečný mls",
  "Jablečný pudink",
  "Jablečný salát se zeleninou a jogurtem",
  "Jablečný závin",
  "Jablka s hlávkovým salátem a ořechy",
  "Jablko v županu",
  "Jablkové řezy – moučník",
  "Jablkový dezert",
  "Jablkový závin",
  "Jablíčková pomazánka s mascarpone",
  "Jahelník s banánem a malinami",
  "Jahelník se sušenými švestkami",
  "Jahelník se švestkami",
  "Jahelník se švestkami a jablko-švestkovou omáčkou",
  "Jahodová pomazánka",
  "Jahodový koktejl",
  "Jahody (ovoce)",
  "Japonské rybí filé",
  "Jarní králičí roláda",
  "Jarní pomazánka",
  "Jarní rizoto s kuřecím masem a chřestem",
  "Jarní zeleninová polévka",
  "Jarní závitek",
  "Jazyk uzený vařený",
  "Jazyk vepřový (telecí) na kmíně",
  "Jazyk vepřový (telecí) smažený",
  "Jemná karotková polévka",
  "Jemná polévka z rybího filé",
  "Jemný sýrový krém s cizrnou",
  "Ječné kroupy s tempehem",
  "Jihočeský kapr jordán",
  "Jitrnicový prejt",
  "Jogurtovník",
  "Jogurtová buchta",
  "Jogurtová pochoutka s ananasem",
  "Jogurtový dresink",
  "Jogurtový koláč",
  "Jogurtový závin",
  "Jáhlová kaše",
  "Jáhlová kaše s medem a skořicí",
  "Jáhlová polévka",
  "Jáhlová pomazánka",
  "Jáhlové kuličky s mixovanými jahodami",
  "Jáhlové placičky se zeleninovou oblohou",
  "Jáhlové rizoto",
  "Jáhlový dezert",
  "Jáhlový nákyp",
  "Jáhly",
  "Jáhly s dušenou mrkví a kurkumou",
  "Jáhly s tofu a restovanou zeleninou",
  "Jáhly zapečené s kysaným zelím",
  "Játra dušená na cibulce (vepřová, telecí, hovězí)",
  "Játra vepřová (telecí) smažená",
  "Kachna pečená",
  "Kakao",
  "Kakao granko",
  "Kakao instant",
  "Kakaová pomazánka",
  "Kakaový chlebíček",
  "Kakaový krém",
  "Kantonská játra",
  "Kantonská rýže s bulgurem",
  "Kapr pečený na kmíně",
  "Kapr po novohradsku",
  "Kapr smažený",
  "Kapr v sýrovém těstíčku",
  "Kapucínské vepřové nudličky",
  "Kapusta dušená",
  "Kapustová polévka",
  "Kapustová roláda s masem a rýží",
  "Kapustová sekaná",
  "Kapustové karbanátky",
  "Kapustové pyré, glazírovaná červená cibulka",
  "Kapustový prejt s vepřovým masem",
  "Kapustový salát s rajčaty a cizrnou",
  "Kapustový závitek s masem a mrkví",
  "Kapří karbanátky s celerem",
  "Karamelizovaná karotka na bylinkách",
  "Karamelové mléko",
  "Karbanátek",
  "Karbanátky",
  "Karlovarský guláš",
  "Karotková pomazánka",
  "Kaše bramborová",
  "Kaše krupicová",
  "Kaše rýžová",
  "Kaše rýžová se skořicí",
  "Kaše z míchaných luštěnin",
  "Kaše z ovesných vloček",
  "Kaštanová nádivka",
  "Kedlubnová kaše",
  "Kedlubnová polévka",
  "Kedlubnová polévka s kuřecími játry a ředkvičkami",
  "Kedlubnové zelí",
  "Kedlubnový salát",
  "Kedlubny dušené",
  "Kedlubny na paprice",
  "Kefírové mléko s borůvkami a mandlemi",
  "Kefírový moučník s meruňkami",
  "Kefírový perník se špaldovou moukou",
  "Klopsy na rajčatech",
  "Klopsy na zelenině",
  "Kmínová polévka",
  "Knedlík žemlový",
  "Knedlík žemlový jemný",
  "Knedlíky kynuté ovocné",
  "Knedlíky kynuté s povidly",
  "Knedlíky ovocné z odpalovaného těsta",
  "Knedlíky ovocné z tvarohového těsta",
  "Knedlíky s džemem a kakaovou polevou",
  "Knedlíky švestkové (bramborové)",
  "Knedlíky žemlové jemné (karlovarské, vídeňské)",
  "Kokosová kuřecí prsíčka",
  "Kokosový dezert",
  "Koložvárska kapusta",
  "Koláče",
  "Konfitované kuřecí prso a la bažant",
  "Konfitovaný králík na šalvěji a saturejce",
  "Kotlety pečené",
  "Kotlíkový guláš",
  "Koule z mletého masa",
  "Kovbojské fazole",
  "Kreolská jambalaya",
  "Krkonošská bramborová kaše",
  "Krkonošská cibulačka",
  "Krkonošské kyselo",
  "Krkonošský houbovec",
  "Krkonošský vývar",
  "Krocan na slanině",
  "Kroupová polévka s celestýnskými nudlemi",
  "Krupicové flameri",
  "Krupicové flameri špaldové",
  "Krupicové noky",
  "Krupicový nákyp",
  "Králičí burger",
  "Králičí filetky na olivách",
  "Králičí hřbet s sušenými rajčaty a kapary",
  "Králičí hřbet v petrželi a bylinkách",
  "Králičí kousky",
  "Králičí maso s jablky a mandlemi na zázvoru",
  "Králičí nudličky s hlívou ústřičnou",
  "Králičí nákyp s kysaným zelím",
  "Králičí ragú",
  "Králičí stehno v zázvorovém jogurtu",
  "Králík a la bažant",
  "Králík na houbách",
  "Králík na paprice",
  "Králík na rozmarýnu",
  "Králík na zelenině",
  "Králík na způsob bažanta",
  "Králík po staročesku",
  "Krémová drůbeží polévka",
  "Krémová polévka s karotkou a koriandrem",
  "Krémová polévka z pečené zeleniny",
  "Krémová polévka z červené čočky a pohanky",
  "Krémová polévka z červené řepy s koprem",
  "Krémová polévka z červených paprik s bulgurem",
  "Krémová rýže s hlívou ústřičnou a bylinkami",
  "Krůta pečená na másle",
  "Krůta pečená s nádivkou",
  "Krůta po dalmatinsku",
  "Krůtí kapsičky plněné sýrem a jablky",
  "Krůtí kuličky s kapustou obalené ve vločkách",
  "Krůtí kuličky se sýrovo-bylinkovým přelivem",
  'Krůtí maso a "sójové maso" v mrkvi',
  "Krůtí maso na pórku se sójovými boby",
  "Krůtí maso po myslivecku",
  "Krůtí maso s tofu sýrem a zeleninou",
  "Krůtí maso v mrkvi",
  "Krůtí maso zapečené s bramborami",
  "Krůtí maso zapečené se zeleninou a rýží",
  "Krůtí medailonky na zázvoru",
  "Krůtí nudličky s pórkem a žampióny",
  "Krůtí plátky po staročesku",
  "Krůtí plátky s hořčicovou omáčkou",
  "Krůtí plátky zapečené s nivou",
  "Krůtí po maďarsku",
  "Krůtí prsa s broskví a sýrem",
  "Krůtí prsíčko s ratatouille",
  "Krůtí roláda plněná cizrnou a barevnými paprikami",
  "Krůtí roláda se špenátem a vejci",
  "Krůtí roláda se šunkou a sýrem",
  "Krůtí závin",
  "Krůtí závitek s hlívou a špenátem",
  "Krůtí závitek s lučinou na rajčatech",
  "Kukuřičná kaše s meruňkami",
  "Kukuřičná polenta",
  "Kukuřičná polenta zapečená",
  "Kukuřičná polévka",
  "Kukuřičný karbanátek",
  "Kukuřičný krém",
  "Kukuřičný salát s olivami a paprikou",
  "Kulajda",
  "Kuskus",
  "Kuskusové koláčky",
  "Kuskusové koule",
  "Kuskusové rizoto s robi masem a řapíkatým celerem",
  "Kuskusové zeleninové rizoto s tofu sypané eidamem",
  "Kuskusový dezert se švestkami",
  "Kuskusový dezert s kukuřicí a smetanou",
  "Kuskusový nákyp",
  "Kuře dušené",
  "Kuře na jogurtu",
  "Kuře na medu",
  "Kuře na oregánu",
  "Kuře na paprice",
  "Kuře na rozmarýnu",
  "Kuře na způsob bažanta",
  "Kuře na česneku",
  "Kuře pečené",
  "Kuře pečené na leču",
  "Kuře pečené na zelí i.",
  "Kuře pečené na zelí ii.",
  "Kuře pečené s nádivkou",
  "Kuře pizzaiola",
  "Kuře plněné",
  "Kuře plněné nádivkou z rýže a žampionů",
  "Kuře po baskicku, rýže",
  "Kuře po hanácku",
  "Kuře po zahradnicku",
  "Kuře po řecku",
  "Kuře zadělávané",
  'Kuřecí "křupeto"',
  "Kuřecí guláš",
  "Kuřecí hamburger",
  "Kuřecí játra dušená",
  "Kuřecí karbanátek s kapustou, pohankou a sýrem",
  "Kuřecí kroketa",
  "Kuřecí krémová polévka",
  "Kuřecí kung pao s cizrnou",
  "Kuřecí maso",
  "Kuřecí omelety",
  "Kuřecí paličky na medu",
  "Kuřecí paličky s hořčicovou marinádou",
  "Kuřecí paličky se salátem coleslaw",
  "Kuřecí paličky v polentové krustě",
  "Kuřecí papání",
  "Kuřecí plněná kapsa s bylinkami",
  "Kuřecí plátek v bylinkové marinádě",
  "Kuřecí plátek v mandlové krustě s omáčkou",
  "Kuřecí plátky na jablkách",
  "Kuřecí plátky obalované v kokosu",
  "Kuřecí polévka",
  "Kuřecí polévka s červenou čočkou a zázvorem",
  "Kuřecí prsa",
  "Kuřecí prsa a la báseň i.",
  "Kuřecí prsa a la báseň ii.",
  "Kuřecí prsa dušená na másle",
  "Kuřecí prsa na citrónu",
  "Kuřecí prsa na paprice",
  "Kuřecí prsa po valticku",
  "Kuřecí prsa pod peřinou s dušenou zeleninou",
  "Kuřecí prsa s bylinkovou krustou",
  "Kuřecí prsa s červenou fazolí",
  "Kuřecí prsa smažená",
  "Kuřecí prsa stroganov",
  "Kuřecí prsa v kukuřičné košilce",
  "Kuřecí prsa ve špenátovém kabátku",
  "Kuřecí prsa zapečená",
  "Kuřecí prsa zapečená se zeleninou a sýrem",
  "Kuřecí prsa zapékaná s žampiony a sýrem",
  "Kuřecí prso na hruškách, jogurtový dip",
  "Kuřecí prsíčko plněné sýrovou fáší",
  "Kuřecí přírodní plátek s omáčkou",
  "Kuřecí rizoto se sójovými boby a zeleninou",
  "Kuřecí roláda plněná šunkou, kozím sýrem a kapií",
  "Kuřecí roláda s červenou čočkou a špenátem",
  "Kuřecí směs po čínsku",
  "Kuřecí soté",
  "Kuřecí soté se žampiony, brokolicí a těstovinami",
  "Kuřecí steak s dušenou zeleninou a bylinkami",
  "Kuřecí steak se šlehačkou",
  "Kuřecí steak s bylinkovou zeleninou",
  "Kuřecí stehna na zelenině",
  "Kuřecí stehna na žampiónech",
  "Kuřecí stehna pečená",
  "Kuřecí stehno marengo",
  "Kuřecí stehno na paprice plněné bylinkovou fáší",
  "Kuřecí stehno na rozmarýnu, špenátová nádivka",
  "Kuřecí stehno pečené na kysaném zelí",
  "Kuřecí stehýnka na medu a zázvoru s nádivkou",
  "Kuřecí stehýnka na medu s badyánem",
  "Kuřecí tetrazzini",
  "Kuřecí tikka masala",
  "Kuřecí vývar s jáhlovo-sýrovými noky",
  "Kuřecí závin",
  "Kuřecí závitek",
  "Kuřecí závitek plněný zeleninou",
  "Kuřecí závitek plněný špenátem a mozzarellou",
  "Kuřecí závitek s mrkvovou omáčkou",
  "Kuřecí závitek se slaninou, smetanový špenát",
  "Kuřecí závitek se sušenými rajčaty a špenátem",
  "Kuřecí závitek se špenátem a krabím masem",
  "Kuřecí závitek se špenátovou náplní",
  "Kuřecí závitek se šunkou, sýrem a pórkem",
  "Kuřecí závitek s mozzarellou a listovým špenátem",
  "Kuřecí závitky plněné zeleninou",
  "Kuřecí řízečky v cizrnovém těstíčku i.",
  "Kuřecí řízečky v cizrnovém těstíčku ii.",
  "Kuřecí řízky jako divočina",
  "Květák na mozeček",
  "Květák s vejci jako mozeček",
  "Květák smažený",
  "Květák zapečený s uzeným masem",
  "Květák zapečený",
  "Květák zapékaný s masem",
  "Květákovo-špenátové placičky s bramborovo-celerovým pyré",
  "Květáková polévka",
  "Květáková polévka s pečenou cizrnou",
  "Květáková polévka se zelenými kroužky",
  "Květáková pomazánka",
  "Květákové kari",
  "Květákové krokety",
  "Květákové placičky",
  "Květákové placičky pečené v troubě",
  "Květákové placičky s tarhoňou",
  "Květákové pyré s bramborami, zelenina",
  "Květákové smaženky",
  "Květákové řízečky",
  "Květákový karbanátek se žampiony",
  "Květákový nákyp",
  "Květákový salát",
  "Květákový salát se smetanou",
  "Kyjevský závitek",
  "Kynutý koláč s tvarohem, borůvkami a špaldovou drobenkou",
  "Kynutý závin",
  "Kynutý závin s mákem",
  "Kysané zelí",
  "Kyselice",
  "Káva bílá",
  "Káva mléčná",
  "Kóprová omáčka",
  "Křehké kuře",
  "Křehké řezy",
  "Křehký koláč",
  "Křupavé kuře",
  "Lasagne",
  "Lasagne s hovězím masem a cuketou",
  "Lasagne s mletým masem a rajčaty",
  "Lasagne s tvarohovou náplní",
  "Lasagne se zeleninovou směsí",
  "Lasagne se špenátem a nivou",
  "Lasagne se špenátem a ricottou",
  "Lasagne se špenátovými listy a uzeným tofu",
  "Lasagne se žampiony a špenátem",
  "Lasagne s kuřecím masem a zeleninou",
  "Ledový salát",
  "Lehký jáhlový dezert s lesním ovocem",
  "Lečo",
  "Lečo s vejci a uzeninou",
  "Libečková pomazánka",
  "Libocká krůta",
  "Lilek pečený",
  "Lilek zapečený v bramborách",
  "Lobkovický kuřecí závitek",
  "Losos",
  "Lososové karbanátky",
  "Lososový krém",
  "Lovecký závitek",
  "Luhačovický špaček",
  "Luštěninovo-mrkvové karbanátky",
  "Luštěninová polévka",
  "Luštěninová polévka s cizrnovým kapáním",
  "Luštěninová směs",
  "Luštěninové rizoto s kroupami a bulgurem",
  "Luštěninové rizoto se šmakounem",
  "Luštěninový prejt",
  "Lázeňské filé",
  "Lívance",
  "Lívance s mrkví a sýrem",
  "Lívance s ovesnými vločkami",
  "Lívanečky s ovesnými vločkami",
  "Lívanečky z kefíru",
  "Mahi-mahi filety zapečené s brokolicí a sýrem",
  "Mahi-mahi na žampionech",
  "Mahi-mahi s balsamikovo-zázvorovou glazurou",
  "Mahi-mahi s česnekovým dipem a mátou",
  "Mahi-mahi se žampiony",
  "Mahi-mahi v česnekové omáčce",
  "Majonézové koblížky – moučník",
  "Majoránkové kroupoto",
  "Makarská pochoutka",
  "Makaróny zapečené s rybou",
  "Makedonské hovězí nudličky",
  "Makedonský tokáň z kuřecího masa",
  "Makovec",
  "Makovec se špaldovou moukou",
  "Makové překvapení",
  "Malkao",
  "Mandarinkové kuře",
  "Marinované drůbeží plátky",
  "Maso na čínský způsob",
  "Masová polévka se špaldou",
  "Masová směs s robi",
  "Masová směs se žampiony a zeleninou",
  "Masové karbanátky s brokolicí a květákem",
  "Masové knedlíky dušené",
  "Masové koule v rajčatové omáčce",
  "Masové krokety",
  "Masové kuličky s jablky a pohankou",
  "Masové kuličky v koprové omáčce",
  "Masové kuličky v rajčatové omáčce",
  "Masové kuličky ve švestkové omáčce",
  "Masové kuličky zapečené s těstovinami, špenátem a rajčaty",
  "Masové nudličky s jemnou omáčkou ze smetany",
  "Masový nákyp",
  "Masový puding",
  "Maďarská rybí polévka",
  "Melounový fresh nápoj",
  "Melounový salát",
  "Mexická fazoláda",
  "Mexická pánev",
  "Mexické karbanátky",
  "Mexický fazolový salát",
  "Mexický guláš",
  "Mexický salát",
  "Mexický salát s rukolou a sýrem",
  "Mexický salát z čínského zelí",
  "Milánské zapečené brambory",
  "Milé filé",
  "Minestrone polévka i.",
  "Minestrone polévka ii.",
  "Minestrone polévka iii.",
  "Minestrone polévka s opraženým pečivem",
  "Minichlebíček s tuňákovou pomazánkou",
  "Mleté balenky",
  "Mleté masové válečky s nivou",
  "Mleté řízky z králíka",
  "Mléko",
  "Mléčný koktejl s jahodami a jogurtem",
  "Monte od maminky",
  "Moravský vrabec",
  "Moučník",
  "Moučník s oříšky, s tvarohovým krémem a",
  "Mozaiková pomazánka",
  "Mozaiková roláda",
  "Mozaiková sekaná",
  "Mozeček s vejci (vepřový, telecí, hovězí)",
  "Mořský úhoř s omáčkou z nivy",
  "Mošty",
  "Mrkev dušená",
  "Mrkev dušená s hráškem",
  "Mrkev s hráškem na smetaně",
  "Mrkvovo-zázvorový krém s pažitkou",
  "Mrkvová polévka",
  "Mrkvová pomazánka",
  "Mrkvové karbanátky",
  "Mrkvové muffiny",
  "Mrkvové placičky",
  "Mrkvové placky",
  "Mrkvový koláč",
  "Mrkvový košíček",
  "Mrkvový krém",
  "Mrkvový salát",
  "Muffiny",
  "Musaka se sekaným květákem",
  "Myslivecká směs s kuřecími játry",
  "Myslivecké kotlety",
  "Míchanice po chalupářsku",
  "Míchaná zelenina dušená",
  "Míchaný listový salát",
  "Míchaný ovocný salát s bulgurem",
  "Míchaný ovocný salát s tvarohovým krémem",
  "Míchaný zeleninový salát",
  "Měkoučké řezy",
  "Mřížkový koláč s jablky",
  "Nastavovaná kaše",
  "Neapolský těstovinový salát",
  "Nebeský bulgur",
  "Nivové placičky s dušenou zeleninou a dresinkem",
  "Nové brambory",
  "Nové zemiaky s tvarohom",
  "Nudle s mákem",
  "Nudle s opraženou krupicí",
  "Nudle",
  "Nudle s tvarohem - slané",
  "Nudle se šunkou",
  "Nudlový nákyp",
  "Nudlový nákyp s masem a sýrem",
  "Nákyp nudlový",
  "Nákyp rýžový",
  "Nákyp tvarohový",
  "Nákyp z rybího filé",
  "Nákyp z růžičkové kapusty",
  "Nákyp z těstovinové rýže",
  "Námořnické maso",
  "Nátierka z rybieho filé",
  "Odpalované pusinky",
  "Okoun nilský na zelenině a žampionech",
  "Okurková limonáda",
  "Okurkový salát",
  "Okurkový salát s paprikami",
  "Okurkový salát se smetanou",
  "Okurkový salát se zakysanou smetanou a koprem",
  "Omeleta s hráškem",
  "Omeleta s hráškom",
  "Omáčka choron",
  "Omáčka houbová",
  "Omáčka játrová",
  "Omáčka koprová",
  "Omáčka křenová",
  "Omáčka okurková",
  "Omáčka rajčatová",
  "Omáčka česneková",
  "Omáčka žampiónová",
  "Otavské špalíčky",
  "Ovocná omáčka",
  "Ovocné knedle zo zemiakového cesta",
  "Ovocné knedle z krupicového cesta",
  "Ovocné knedlíky z bramborového těsta",
  "Ovocný krém",
  "Ovocný salát",
  "Ořechovo-mrkvové řezy s krémovou polevou",
  "Paella s tuňákem a zeleninou",
  "Paella – španělské rizoto",
  "Palačinky",
  "Palačinky plněné mrkvovo-jablečnou náplní",
  "Palačinky plněné sójovou směsí",
  'Palačinky s "tofu tvarohem" a ovocem',
  "Palačinky se zavařeninou",
  "Palačinky se zeleninovou směsí",
  "Palačinky se špenátem a lučinou",
  "Pangasius v cizrnové košilce",
  "Pangasius ze švédska s bramborami a zeleninou",
  "Panna cotta",
  "Paprika plněná vaječnou směsí",
  "Paprika plněná zeleninovou rýží",
  "Paprikový lusk plněný houbami",
  "Paprikový salát",
  "Paprikový salát se zelím",
  "Papriky plněné zeleninou",
  "Paradajková omáčka",
  "Paradajková polievka s ryžou",
  "Paradajková polievka so syrom",
  "Pasírované brambory s pórkem",
  "Patisonové ragú",
  "Patisony na smetaně",
  "Pažitková omáčka",
  "Penne s kuřecím masem a bazalkovým pestem",
  "Pepkova omeleta s dušenou zeleninou",
  "Perník s ovesnými vločkami",
  "Pestrobarevný tuňákový salát se slunečnicovým semínkem",
  "Pestré špagety (puttanesca)",
  "Pestrý salát s cizrnou",
  "Pestrý zeleninový talíř s kousky tuňáka",
  "Petrželová polévka krémová s mrkvovými krutony",
  "Pečená jablka s vanilkovým krémem",
  "Pečená králičí stehýnka na rozmarýnu a šalvěji",
  "Pečená kuřecí prsa, jemná kari omáčka",
  "Pečená tilápie se sýrovo-cizrnovou omáčkou",
  "Pečené karbanátky se žampiony",
  "Pečené nové brambory s bylinkovým dipem",
  "Pečené papriky plněné",
  "Pečený karbanátek z hovězího masa",
  "Pečený králík s bylinkami a česnekem",
  "Pečený králík v marinádě s paprikou",
  "Pečený losos s cornflakes a sýrem",
  "Pečený závitek z tresky plněný lososem",
  "Pikantní kuře s loupanými rajčaty a ananasem",
  "Pikantní sójové kostky na kari",
  "Pikantní zeleninový koláč",
  "Pirožky s masovou náplní",
  "Pizza",
  "Pizza i.",
  "Pizza ii.",
  "Pizza z bramborového těsta",
  "Piškotová roláda",
  "Piškótový závin",
  "Placičky s celerem a ovesnými vločkami",
  "Placičky z karotky a brokolice s tvarohovým dipem",
  "Placičky ze sumečka afrického a kapusty",
  "Platýs na másle",
  "Plnené paradajky",
  "Plnený kapustový závitok",
  "Plněná kapusta",
  "Plněná papriková lodička pangasiem",
  "Plněná rajčata",
  "Plněné žampionové hlavičky",
  "Plněný paprikový lusk",
  "Plněný vepřový řízek",
  "Plněný zelný list pohankovo-čočkovou fáší",
  "Plzěný zelný závitek",
  "Plíčky na smetaně (vepřové, telecí)",
  "Pochoutka z hovězího masa",
  "Podmáslová polévka",
  "Podzimní grilovaná zelenina",
  "Poděbradské maso",
  "Pohanková  polévka",
  "Pohanková kaše s dušenými jablky",
  "Pohanková polévka",
  "Pohanková polévka krémová",
  "Pohanková polévka na kyselo",
  "Pohanková polévka s játrovými knedlíčky",
  "Pohanková polévka s červenou čočkou",
  "Pohanková polévka se sýrem a žampiony",
  "Pohanková pomazánka",
  "Pohanková pomazánka s brynzou",
  "Pohanková pomazánka s povidly a slunečnicovými semínky",
  "Pohanková rýže i.",
  "Pohanková rýže ii.",
  "Pohankové flameri s pečenými hruškami",
  "Pohankové kasoto",
  "Pohankové krupoto se žampiony",
  "Pohankové noky",
  "Pohankové palačinky",
  "Pohankové rizoto s krůtím masem a cizrnou",
  "Pohankové rizoto se žampionovými plátky a čerstvou paprikou",
  "Pohankový knedlík",
  "Pohankový nákyp",
  "Pohankový prejt se zelím",
  "Polenta s cherry rajčátky a parmazánem",
  "Polentová kaše se špenátem a parmazánem",
  "Polentové knedlíky",
  "Polentové krokety",
  "Polentový dezert",
  "Polentový koláč se švestkami",
  "Polévka",
  'Polévka "kfc" (kreativní francouzská cibulačka)',
  "Polévka ,,kfc“ (kreativní francouzská cibulačka)",
  "Polévka bramborová",
  "Polévka bulharská květáková",
  "Polévka celerová",
  "Polévka cibulová",
  "Polévka drožďová",
  "Polévka dršťková",
  "Polévka drůbková",
  "Polévka drůbková jemná",
  "Polévka drůbková jemná s nudlemi",
  "Polévka drůbková s nudlemi",
  "Polévka dýňová",
  "Polévka fazolová",
  "Polévka fazolová s párkem",
  "Polévka frankfurtská",
  "Polévka gulášová",
  "Polévka horačka",
  "Polévka houbová horácká",
  "Polévka houbová z hlívy ústřičné (á la dršťková)",
  "Polévka hovězí",
  "Polévka hovězí s domácími nudlemi",
  "Polévka hovězí s játrovými knedlíčky",
  "Polévka hovězí s játrovými noky",
  "Polévka hovězí s kapustou a rýží",
  "Polévka hovězí s kapáním",
  "Polévka hovězí s krupicovými noky",
  "Polévka hovězí s krupkami",
  "Polévka hovězí s masem a domácími nudlemi",
  "Polévka hovězí s masem a rýží",
  "Polévka hovězí s masovými knedlíčky",
  "Polévka hovězí s ovesnými vločkami",
  "Polévka hovězí s rýží a hráškem",
  "Polévka hovězí s těstovinami",
  "Polévka hovězí s vaječnou sedlinou",
  "Polévka hovězí s vaječnou sedlinou a šunkou",
  "Polévka hovězí s vaječným svítkem",
  "Polévka hovězí se slezinovou rýží",
  "Polévka hovězí se strouháním",
  "Polévka hovězí se sýrovým kapáním",
  "Polévka hovězí se sýrovým svítkem",
  "Polévka hovězí se zeleninovým svítkem",
  "Polévka hovězí se špenátovým svítkem",
  "Polévka hovězí se šunkovým svítkem",
  "Polévka hrachová",
  "Polévka hrachová s uzeninou",
  "Polévka hrstková",
  "Polévka hráškový krém",
  "Polévka kaldounek",
  "Polévka kapustová",
  "Polévka kapustová s uzeným masem",
  "Polévka kedlubnová",
  "Polévka kmínová",
  "Polévka kmínová s houskou",
  "Polévka kmínová s kapáním",
  "Polévka koprová (kulajda)",
  "Polévka krupicová",
  "Polévka květáková",
  "Polévka masový krém",
  "Polévka mléčná",
  "Polévka mozečková",
  "Polévka mrkvová",
  "Polévka petrželová",
  "Polévka pórková",
  "Polévka pórková s kapáním",
  "Polévka ragú",
  "Polévka ragú s houskovými knedlíčky",
  "Polévka ragú – zavářka knedlíčky",
  "Polévka rajčatová",
  "Polévka rajčatová s kapáním",
  "Polévka rajčatová s ovesnými vločkami",
  "Polévka rajčatová s těstovinou",
  "Polévka ruský boršč",
  "Polévka rybí",
  "Polévka rýžová",
  "Polévka rýžová s mlékem a vejci",
  "Polévka s kapřími noky",
  "Polévka selská i.",
  "Polévka selská ii.",
  "Polévka selská zelňačka",
  "Polévka slepičí",
  "Polévka slepičí krémová s hráškem",
  "Polévka slepičí s nudlemi",
  "Polévka sýrová cibulačka",
  "Polévka vločková",
  "Polévka z celeru, řapíkatého celeru a cizrny",
  "Polévka z fazolových lusků",
  "Polévka z fazolových lusků s kapáním",
  "Polévka z hlávkového zelí",
  "Polévka z hlívy ústřičné",
  "Polévka z hlívy ústřičné a la dršťková",
  "Polévka z hlívy ústřičné s brokolicí a sýrem",
  "Polévka z jarní cibulky",
  "Polévka z jarní zeleniny",
  "Polévka z jarní zeleniny s cizrnovými nočky",
  "Polévka z krájených rajčat s červenou čočkou",
  "Polévka z kysaného zelí",
  "Polévka z kysaného zelí s párkem",
  "Polévka z listového špenátu",
  "Polévka z lososa se smetanou",
  "Polévka z mladé cukety s krutony",
  "Polévka z míchaných luštěnin s uzeným tofu",
  "Polévka z rybího filé",
  "Polévka z rybího masa s krabí příchutí",
  "Polévka z tykve",
  "Polévka z vaječné jíšky",
  "Polévka z červené čočky",
  "Polévka z červené čočky a zeleniny",
  "Polévka z červené čočky se zeleninou a krupkami",
  "Polévka z červené řepy a s tvarohovými nočky",
  "Polévka z řapíkatého celeru s dýňovými semínky",
  "Polévka ze zeleného hrášku",
  "Polévka ze zelených fazolek s bramborem a smetanou",
  "Polévka ze špaldové krupice",
  "Polévka zeleninová",
  "Polévka zeleninová s drožďovými knedlíčky",
  "Polévka zeleninová se sýrovým kapáním",
  "Polévka z kysaného zelí – slovenská",
  "Polévka česneková",
  "Polévka čočková",
  "Polévka špenátová",
  "Pomazánka",
  "Pomazánka brokolicová",
  "Pomazánka drožďová",
  "Pomazánka drožďová s uzeným masem",
  "Pomazánka jáhlová",
  "Pomazánka játrová",
  "Pomazánka lososová",
  "Pomazánka maslová",
  "Pomazánka mrkvová",
  "Pomazánka norská",
  "Pomazánka s rajčaty a bazalkou",
  "Pomazánka salámová",
  "Pomazánka sardinková",
  "Pomazánka sardinková s avokádem",
  "Pomazánka sardinková s tvarohem a celerem",
  "Pomazánka sardinková se zeleninou a vejci",
  "Pomazánka sojová",
  "Pomazánka sýrová",
  "Pomazánka sýrová s celerem",
  "Pomazánka sýrová s kapií",
  "Pomazánka sýrová s nivou",
  "Pomazánka sýrová s pažitkou",
  "Pomazánka sýrová s vejcem a zeleninou",
  "Pomazánka sýrová se strouhaným eidamem",
  "Pomazánka sýrová se šunkou",
  "Pomazánka tuňáková se sýrem a ovesnými vločkami",
  "Pomazánka tvarohovo smetanová s vejci a salátovou okurkou",
  "Pomazánka tvarohová",
  "Pomazánka tvarohová s kapií",
  "Pomazánka tvarohová s mrkví",
  "Pomazánka tvarohová s mrkví a vejcem",
  "Pomazánka tvarohová s pažitkou",
  "Pomazánka tvarohová s červenou řepou a vejcem",
  "Pomazánka vaječná",
  "Pomazánka vaječná s pórkem",
  "Pomazánka vaječná se šunkou",
  "Pomazánka vajíčková",
  "Pomazánka z aljašské tresky s lučinou a křenem",
  "Pomazánka z hovězího masa",
  "Pomazánka z krabích tyčinek s křenem",
  "Pomazánka z kuřecího masa",
  "Pomazánka z lososa a fazolí",
  "Pomazánka z lososa s vařenými bramborami",
  "Pomazánka z lososa s vlašskými ořechy",
  "Pomazánka z lučiny a bílé ředkve",
  "Pomazánka z lučiny s jablky a slunečnicovými semínky",
  "Pomazánka z makrely",
  "Pomazánka z makrely s tvarohem a ovesnými vločkami",
  "Pomazánka z nivy",
  "Pomazánka z olejovek",
  "Pomazánka z paštiky",
  "Pomazánka z ryb v tomatě",
  "Pomazánka z rybího filé",
  "Pomazánka z rybího filé s bylinkami",
  "Pomazánka z taveného sýra",
  "Pomazánka z taveného sýra a ředkvičkou",
  "Pomazánka z telecího masa",
  "Pomazánka z tofu",
  "Pomazánka z tresčích jater",
  "Pomazánka z tuňáka s kukuřicí",
  "Pomazánka z uzenáčů",
  "Pomazánka z vepřového bůčku",
  "Pomazánka z vepřových škvarků",
  "Pomazánka z červené čočky",
  "Pomazánka z červené čočky s paprikou",
  "Pomazánka z červených fazolí",
  "Pomazánka ze sójových bobů",
  "Pomazánka ze sýru  cottage s jablkem a mandarinkou",
  "Pomazánka ze sýru cottage",
  "Pomazánka zeleninová",
  "Pomazánka špenátová",
  "Pomazánka šunková",
  "Pomazánka švédská",
  "Pošírované kuřecí kuličky na rajčatové omáčce",
  "Pošírovaný filet mahi-mahi",
  "Prejt z červené čočky s kysaným zelím",
  "Provensálský králík",
  "Pstruh lososový",
  "Pstruh po mlynářsku",
  "Puding",
  "Pudink",
  "Pudink",
  "Píprlák",
  "Písecké vločkové pusinky s citrónovým sorbetem",
  "Pórková polévka",
  "Pórková polévka s krupicovými nočky",
  "Pórková polévka s červenou čočkou",
  "Pórkové flíčky",
  "Pórkové karbanátky",
  "Pórkový salát s jablky a mrkví",
  "Pětizrnný karbanátek",
  "Přílohová zelenina",
  "Přírodní filet z králíka na bylinkách",
  "Přírodní placičky z rybího filé s celerem",
  "Přírodní vepřová panenka",
  "Pštrosí vejce",
  "Quiche - slaný špenátový koláč",
  "Quinoa s tofu na jihozápadní způsob",
  "Radicchio s římským hrachem",
  "Radvanský guláš",
  "Ragú polévka",
  "Ragú ze šmakouna",
  "Rajská omáčka s hovězím masem vařeným přes noc",
  "Rajská polévka s ovesnými vločkami",
  "Rajčata plněná masovou směsí",
  "Rajčata plněná vejci a sýrem",
  "Rajčatová polévka",
  "Rajčatová polévka s kousky rajčat a mozzarellou",
  "Rajčatová polévka s ovesnými vločkami",
  "Rajčatová rybí polévka",
  "Rajčatový salát",
  "Rajčatový salát s cottage sýrem",
  "Rajčatový salát s květákem",
  "Rajčatový salát s pórkem",
  "Rajče plněné kuskusem a nivou",
  "Rakouská pomazánka erdapfelkas",
  "Rakovnický závitek",
  "Ratatouille s divokou rýží a mozzarellou",
  "Restovaná zelenina",
  "Restované zelené fazolky",
  "Restovaný bulgur s červenými fazolemi, hlívou a s kapiemi",
  "Rizoto s fazolemi a zeleninou sypané sýrem",
  "Rizoto s houbami",
  "Rizoto s houbami, masem a zeleninou",
  "Rizoto s hráškem a žampiony",
  "Rizoto s kuřecím a krabím masem",
  "Rizoto s lososem, cherry rajčaty a hráškem",
  "Rizoto s masem a sýrem",
  "Rizoto se sójovými boby a houbami",
  "Rizoto se zeleninou a drůbežím masem",
  "Rizoto srbské",
  "Rizoto z benátek",
  "Rizoto z drůbeže",
  "Rizoto z drůbežích žaludků",
  "Rizoto z kuskusu s vepřovým masem a červenou čočkou",
  "Rizoto z kuřecího masa",
  "Rizoto z pohanky",
  "Rizoto z vepřového masa",
  "Rizoto zeleninové s hlívou ústřičnou a sýrem",
  "Robi po mexicku",
  "Rohlík s pomazánkovým máslem",
  "Rolky z listového těsta",
  "Roláda z mahi-mahi plněná lososem",
  "Roláda z vepřového masa",
  "Romanesco vařené se sýrovou omáčkou",
  "Rozhuda",
  "Rozinková rýže",
  "Rozmarýnový špíz se štikozubcem, lososem a s citróny",
  "Roštěnky s hráškem a karotkou",
  "Roštěná bratislavská",
  "Roštěná po švábsku",
  "Rožnovská kapsa",
  "Rubínová polévka",
  "Ryba hoki s pórkovou omáčkou",
  "Ryba po provensálsku",
  "Ryba v rajské omáčce",
  "Rybí biftečky",
  "Rybí filet v hořčičném obalu",
  "Rybí filet v sýrové peřince",
  "Rybí filety se zakysanou smetanou a hořčicí",
  "Rybí filé",
  "Rybí filé liu",
  "Rybí filé na bylinkách",
  "Rybí filé na celeru a pórku",
  "Rybí filé na leču",
  "Rybí filé na másle",
  "Rybí filé na rajčatovém protlaku",
  "Rybí filé na smetaně",
  "Rybí filé na česneku a slanině",
  "Rybí filé pečené na cuketách a smetaně",
  "Rybí filé pečené na másle",
  "Rybí filé pečené s mandlemi",
  "Rybí filé po mexicku",
  "Rybí filé po rožmbersku",
  "Rybí filé po řecku",
  "Rybí filé s jablky a celerem",
  "Rybí filé s křenem",
  "Rybí filé smažené",
  "Rybí filé v zakysané smetaně",
  "Rybí filé zapečené",
  "Rybí filé zapečené s ovesnými vločkami a zeleninou",
  "Rybí filé zapékané s bešamelem",
  "Rybí filé zapékané",
  "Rybí karbanátek",
  "Rybí karbanátky s bylinkovým dipem",
  "Rybí kari",
  "Rybí kostky v cuketě",
  "Rybí koule",
  "Rybí krokety po dalmátsku",
  "Rybí maso",
  "Rybí nákyp",
  "Rybí paella po česku",
  "Rybí paprikáš",
  "Rybí polévka",
  "Rybí polévka s celestýnskými nudlemi",
  "Rybí polévka s cizrnovými nočky",
  "Rybí polévka s fritátovými nudlemi a zeleninou",
  "Rybí polévka s kari",
  "Rybí polévka s opečenými rohlíčky",
  "Rybí polévka s vařeným vejcem",
  "Rybí ragú z aljašské tresky",
  "Rybí salát",
  "Rybí těstovinové rizoto",
  "Rybí vydatná polévka",
  "Rybí závitek",
  "Rybí závitek se špenátem a sýrem",
  "Rybí závitky",
  "Rybí závitky se smetanou",
  "Rybí špíz s anglickou slaninou a zeleninou",
  "Rybí šči",
  "Rychnovský vepřový kotouč",
  "Rychvalďáček",
  "Rýže arborio s kuřecím masem a listovým špenátem",
  "Rýže bombaj",
  "Rýže dušená",
  "Rýže dušená s quinoou",
  "Rýže mozaiková",
  "Rýže pohanková",
  "Rýže pórková",
  "Rýže s dary moře",
  "Rýže s vepřovým masem, paprikami a rajča",
  "Rýže s čočkou beluga",
  "Rýže s čočkou mung dal",
  "Rýžová kaše s borůvkami",
  "Rýžová pomazánka",
  "Rýžová pomazánka s banány",
  "Rýžový koláč zapečený s cuketami a fetou",
  "Rýžový nákyp",
  "Rýžový pudink",
  "Rýžový salát",
  "Růžičková kapusta s baby mrkvičkou a tymiánovými bramborami",
  "Salát",
  "Salát hawai",
  "Salát hlávkový",
  "Salát mrkvový",
  "Salát mrkvový s meruňkovým kompotem",
  "Salát mrkvový se zelím",
  "Salát okurkový",
  "Salát paprikovo-rajčatový",
  "Salát polníček",
  "Salát radicchio s hruškou",
  "Salát rajčatový s cibulí",
  "Salát rajčatový s vejci a sýrem",
  "Salát redkvičkový",
  "Salát s kuřecím masem a majonézou",
  "Salát s mungo klíčky a sýrem tofu",
  "Salát sýrový",
  "Salát tabouleh",
  "Salát z brokolice a rajčat se zakysanou",
  "Salát z bílého hlávkového zelí",
  "Salát z fazolových lusků",
  "Salát z hlávkového zelí",
  "Salát z hlávkového zelí s mrkví, pomerančem a kiwi",
  "Salát z kysaného zelí (zelný)",
  "Salát z mladého chřestu",
  "Salát z mrkve a celeru",
  "Salát z obou zelí",
  "Salát z tarhoni s čočkou",
  "Salát z těstovin, krabích tyčinek surimi a tofu",
  "Salát z těstovin, kuřecího masa a majoné",
  "Salát z těstovin, tuňáka a pórku",
  "Salát z čekankových puků s jablky, mrkví",
  "Salát z černé ředkve",
  "Salát z červené čočky",
  "Salát z červené řepy s celerem",
  "Salát z červeného hlávkového zelí",
  "Salát z červeného zelí s karotkou a jablkem",
  "Salát z čínského zelí",
  "Salát z čínského zelí s jablky a mrkví",
  "Salát z čínského zelí s kukuřicí",
  "Salát z čínského zelí s pomerančem a jogurtem",
  "Salát ze zelí, rajčat a jablek",
  "Salát zeleninový",
  "Salát z kyselého zelí",
  "Salát á la stefano",
  "Sardinková pomazánka",
  "Segedínsky guláš",
  "Segedínská rybí polévka",
  "Segedínský guláš",
  "Sekaná",
  "Sekaná drůbeží (mražený polotovar)",
  "Sekaná dušená",
  "Sekaná pečeně",
  "Sekaná pečeně se sójovými boby",
  "Sekaná se zeleninou na plechu",
  "Sekaná svíčková",
  "Sekaná z rybího filé",
  "Sekaná zahradnická",
  "Sekaná štefánská",
  "Sekaná štěpánská",
  "Sekaný máslový řízek",
  "Sekaný řízek po maďarsku",
  "Sekaný řízek přírodní",
  "Sekaný řízek telecí (máslový řízek)",
  "Sekaný špalíček s cizrnou",
  "Selská polévka",
  "Sicilská rybí polévka",
  "Sicilská tomatová polévka",
  "Sicilské špagety",
  "Skopové na paprice",
  "Skopové na česneku",
  "Skopové v kapustě",
  "Skořicovníky – moučník",
  "Sladká jablka valdostana",
  "Slané tyčinky",
  "Slepice na paprice",
  "Slovenská zelná polévka",
  "Slovácké vepřové žebírko",
  "Smažená cuketa",
  "Smažená kuřecí stehna toskánská",
  "Smažené vdolky",
  "Smažený celer",
  "Smažený vdoleček",
  "Smetanová omáčka",
  "Smetanové brambory",
  "Smetanové brambory s brokolicí a šunkou",
  "Smetanové rizoto s hráškem",
  "Smetanový listový špenát s cizrnou",
  "Smetanový špenát s cizrnou a opečeným bramborem",
  "Smoothie",
  "Srbská čorba",
  "Srbské fazole v palačince",
  "Srdce na slanině (hovězí,vepřové,telecí)",
  "Srdce na smetaně",
  "Staropražské pečené kuře",
  "Staropražské psaníčko",
  "Staročeské masové karbanátky s luštěninou",
  "Staročeské mrkvance",
  "Steak z lososa na zelených fazolových luscích",
  "Steak z lososa pečený v alobalu",
  "Steak z tuňáka s celerovým pyré",
  "Strapačky s kapustou",
  "Strapačky",
  "Střapatá rýže",
  "Střapatá rýže s pohankou",
  "Sumeček africký po indicku",
  "Sumeček africký s italskou čočkou",
  "Sumeček africký s lasagnemi",
  "Sumeček africký v hořčičné omáčce",
  "Sváteční salát ze surimi tyčinek",
  "Svíčková na smetaně",
  "Svíčková z krůtího masa",
  "Syrakuzské špagety",
  "Sójová pomazánka",
  "Sójové nudličky se zeleninou a kuskusem",
  "Sójový koláč",
  "Sójový tempeh s baby mrkvičkou a hráškem",
  "Sýrová polévka",
  "Sýrová sekaná s amarantem",
  "Sýrové brambory s krůtím masem a cibulkou",
  "Sýrové bramboráčky",
  "Sýrové placičky s kukuřicí",
  "Sýrové placičky z eidamu a nivy",
  "Sýrové tortellini s rajčaty a parmazánem",
  "Sýrový karbanátek",
  "Sýrový nákyp",
  "Sýrový salát s ananasem",
  "Sýrový salát s hroznovým vínem a ořechy",
  "Tagliatelle s rukolovým pestem, sušenými rajčaty a ořechy",
  "Tagliatelle se žampiony, cuketou a parmazánem",
  "Tarhoňa s ratatouille",
  "Tarhoňa s rybízovým přelivem",
  "Tarhoňa se zeleninou a tofu",
  "Tarhoňa se zeleninou, červenou čočkou a sýrem",
  "Tatranská pečeně",
  "Taštičky z listového těsta s rybí náplní",
  "Telecí kýta špikovaná",
  "Telecí maso pečené",
  "Telecí na hrášku",
  "Telecí na kmíně",
  "Telecí na paprice",
  "Telecí na pražský způsob",
  "Telecí na smetaně",
  "Telecí na zahradnický způsob",
  "Telecí pečeně",
  "Telecí přírodní",
  "Telecí přírodní řízky",
  "Telecí ragú",
  "Telecí závitek",
  "Telecí řízek smažený",
  "Teplý podzimní salát z pečených brambor",
  "Teplý rýžový salát s uzeným tofu",
  "Teplý těstovinový salát s hovězím masem a zeleninou",
  "Testovací pal",
  "Tilápie",
  "Tilápie na zázvoru s arašídy",
  "Tilápie s krustou",
  "Tilápie v kořenové zelenině",
  "Tilápie zapečená s brokolicí a sýrem",
  "Tilápie zapečená s rajčaty a sýrem",
  "Tofu jako humrový krém",
  "Tofu na paprice",
  "Tofu na zelenině",
  "Tofu s paprikou a rajčaty",
  "Tofu s pórkem a brokolicí",
  "Tondovo kuře",
  "Tortellinový salát",
  "Tortilla plněná směsí sumečka afrického, fazolí a ledového salátu",
  "Tortilla plněná vepřovým masem a zeleninou",
  "Tortilla s hovězím masem",
  "Tortilla zapečená se zeleninou a sýrem",
  "Trojbarevný tvarohový moučník",
  "Tuňák s ledovým salátem, vejci a olivami",
  "Tuňák s pestem a těstovinami penne",
  "Tuňák s rýží basmati, ledovým salátem a strouhaným sýrem",
  "Tuňák s těstovinami farfalle, žampiony a smetanou",
  "Tuňák s těstovinami tagliatelle a rajčaty",
  "Tuňáková polévka s bulgurovou zavářkou",
  "Tuňáková pomazánka",
  "Tuňákové lasagne",
  "Tuňákový karbanátek pečený",
  "Tuňákový salát",
  "Tuňákový wrap",
  "Tvaroh s ananasem",
  "Tvarohovo-bramborové placičky",
  "Tvarohová bábovka",
  "Tvarohová pomazánka",
  "Tvarohová pomazánka s avokádem a polníčkem",
  "Tvarohová pomazánka s řeřichou",
  "Tvarohová pribinka",
  "Tvarohové chrupinky",
  "Tvarohové knedlíky s povidly sypané perníkem",
  "Tvarohové kuličky se strouhankou",
  "Tvarohové noky",
  "Tvarohové řezy od babičky",
  "Tvarohové šišky s vanilkovou omáčkou a jahodami",
  "Tvarohový dezert",
  "Tvarohový dezert s jablkovým pyré a jahodami",
  "Tvarohový koláč i.",
  "Tvarohový koláč ii.",
  "Tvarohový krém",
  "Tvarohový krém s ovocným přelivem a müsli",
  "Tvarohový krém s jogurtem, grankem a jahodami",
  'Tvarohový moučník "prošívaná deka"',
  "Tvarohový nákyp, hruškové ragú s rakytníkem",
  "Tvarohový pohár s ovocem",
  "Tvarohový závin",
  "Těstovinová musaka i.",
  "Těstovinová musaka ii.",
  "Těstovinové mušličky s houbami a mascarpone",
  "Těstovinové zeleninové rizoto",
  "Těstovinový salát",
  "Těstovinový salát s bílým jogurtem a cibulovými kroužky",
  "Těstovinový salát s kukuřicí a bílým jogurtem",
  "Těstovinový salát s treskou a zeleninou",
  "Těstovinový salát s tuňákem a zeleninou",
  "Těstovinový salát s čočkou a kuřecím masem",
  "Těstoviny",
  "Těstoviny domácí",
  "Těstoviny fantasio",
  "Těstoviny na způsob italských lasagní",
  "Těstoviny penne s tuňákem a cherry rajčaty",
  "Těstoviny penne s rajčaty",
  "Těstoviny po benátsku s hráškem a vepřovým masem",
  "Těstoviny po boloňsku",
  "Těstoviny po lotrinsku",
  "Těstoviny přílohové",
  "Těstoviny s bazalkovým tofu",
  "Těstoviny s dýňovou omáčkou",
  "Těstoviny s lučinou a uzeným tofu",
  "Těstoviny s masem a zeleninou",
  "Těstoviny s masem, žampiony a zeleninou",
  "Těstoviny s masovými kuličkami a rajčaty",
  "Těstoviny s omáčkou s vepřovým masem a r",
  "Těstoviny s omáčkou z pórku a smetany",
  "Těstoviny s pangasiem a zeleninou",
  "Těstoviny s rajčaty a cuketou",
  "Těstoviny s uzeným tofu",
  "Těstoviny se zeleninou, zapečené",
  "Těstoviny se špenátem a kuřecím masem",
  "Těstoviny se špenátem a sýrem cottage",
  "Těstoviny z jednoho hrnce s červenou čočkou",
  "Těstoviny zapečené s listovým špenátem a sýrem",
  "Těstoviny zapečené s mletým masem a brokolicí",
  "Těstoviny zapečené s tvarohem a jablky",
  "Těstoviny zapečené se sójovou šunkou",
  "Těstoviny zapečené se žampiony",
  "Těstoviny zapékané se sýrem a vejcem",
  "Třešňová (višňová) bublanina",
  "Uherská pečeně",
  "Utajená vepřová játra s krůtím masem",
  "Uzená plec se švestkovou omáčkou",
  "Uzené maso vařené",
  "Uzené tofu v pikantní směsi s jarní zeleninou a žampiony",
  "Uzený losos v širokých nudlích",
  "Vaječná omeleta",
  "Vaječná omeleta s chřestem",
  "Vaječná",
  "Valašská kyselica i.",
  "Valašská kyselica ii.",
  "Valašské frgály i. – těsto",
  "Valašské frgály ii. – náplně",
  "Vanilkový krém",
  "Venkovská pečeně",
  "Vepřenky s cibulí",
  "Vepřová bakoňská kotleta",
  "Vepřová játra po znojemsku",
  "Vepřová játra s bylinkovou šťávou",
  "Vepřová kotleta pečená na kysaném zelí",
  "Vepřová krkovička smažená",
  "Vepřová kýta hamburská",
  "Vepřová kýta na divoko",
  "Vepřová kýta na paprice",
  "Vepřová kýta na smetaně",
  "Vepřová kýta na zelenině s džemem",
  "Vepřová kýta plněná karotkou a řapíkatým celerem",
  "Vepřová kýta přírodní",
  "Vepřová kýta s mrkví",
  "Vepřová pečeně",
  "Vepřová pečeně na zelí",
  "Vepřová pečeně protýkaná zeleninou",
  "Vepřová pečeně s ananasem (broskví)",
  "Vepřová pečeně selská",
  "Vepřová plec",
  "Vepřová plec a la bažant",
  "Vepřová roláda (karlovarský kotouč)",
  "Vepřová žebírka",
  "Vepřové dušené v kapustě",
  "Vepřové kostky po námořnicku",
  "Vepřové kostky s pórkem a lilkem",
  "Vepřové kotlety zapečené v zelenině a bramborami",
  "Vepřové kýta na rajském protlaku",
  "Vepřové ledvinky po italsku",
  "Vepřové maso dušené s čínským zelím",
  "Vepřové maso po provensálsku",
  "Vepřové maso s mrkví a sušenými meruňkami",
  "Vepřové na houbách",
  "Vepřové na kmíně",
  "Vepřové na paprice",
  "Vepřové na žampiónech",
  "Vepřové plátky na kmíně",
  "Vepřové plátky na paprice",
  "Vepřové plátky na zelenině",
  "Vepřové plátky na žampionech",
  "Vepřové plátky na žampiónech",
  "Vepřové plátky s cuketou a rajčaty",
  "Vepřové slezinky na cibulce",
  "Vepřové v kapustě",
  "Vepřové v kedlubnách",
  "Vepřové v mrkvi",
  "Vepřové v zelenině",
  "Vepřové žebírko na kmíně",
  "Vepřové žebírko smažené",
  "Vepřový guláš",
  "Vepřový guláš debrecínský",
  "Vepřový závitek",
  "Vepřový závitek přírodní",
  "Vepřový závitek se sušenými rajčaty a sýrem",
  "Vepřový řízek přírodní",
  "Vepřový řízek smažený",
  "Vesnický nákyp s červenou čočkou",
  "Vihorlatský kuřecí řízek",
  "Vitamínový salát",
  "Vlasové nudle s rajčaty a sýrem",
  "Vločková kaše",
  "Vločková polévka",
  "Vločkové karbanátky",
  "Vločkový dezert s medem a čerstvým ovocem",
  "Voda s citrónem",
  "Voda s ovocným sirupem",
  "Voda se sirupem",
  "Vodnické špenátové placky",
  "Vranovský bifteček",
  "Vydatná rybí polévka",
  "Vývar na polévky",
  "Vývar s hovězím masem a celestýnskými nudlemi",
  "Vývar s rybími nočky a zeleninou",
  "Věneček s vanilkovým krémem",
  "Věneček z odpalovaného těsta s jahodovým krémem",
  "Zahalené rybí filé",
  "Zahradnická polévka",
  "Zahradnická sekaná z pohanky",
  "Zapečená brokolice",
  "Zapečená cuketa se šunkou a žampiony",
  "Zapečená cuketová lodička se sójovým masem",
  "Zapečená kapusta",
  "Zapečená kapusta s pohankou",
  "Zapečená kapusta s rýží a žampiony",
  "Zapečená paprika plněná pohankovo-jahelnou směsí",
  "Zapečená pohanka s červenou čočkou a tofu",
  "Zapečená polenta s rajčaty a parmazánem",
  "Zapečená ryba se zeleninou a pórkem",
  "Zapečené brambory",
  "Zapečené brambory s nivou a žampiony",
  "Zapečené brambory s tofu a brokolicí",
  "Zapečené brambory s červenou čočkou",
  "Zapečené brambory se zeleninou a rybou",
  "Zapečené brambory se zeleninou a červenou čočkou",
  "Zapečené brambory se zeleninou, sýrem tofu a smetanou",
  "Zapečené flíčky s brambory (grenadýrský)",
  "Zapečené halušky se sýrem a rajčatovou omáčkou s fazolemi",
  "Zapečené krůtí medailonky s brokolicí a sýrem",
  "Zapečené kuřecí maso s bramborami a zeleninou",
  "Zapečené kuřecí řízky",
  "Zapečené mleté maso",
  "Zapečené papriky s jáhlovou směsí",
  "Zapečené rybí filé",
  "Zapečené rybí filé s brokolicí a jogurtovým přelivem",
  "Zapečené rybí filé se sýrem a vejci",
  "Zapečené těstoviny",
  "Zapečené těstoviny s brokolicí a sýrem",
  "Zapečené těstoviny s houbami",
  "Zapečené těstoviny s paprikami a cuketou",
  "Zapečené těstoviny s uzeninou",
  "Zapečené těstoviny s vepřovým masem a květákem",
  "Zapečené těstoviny se špenátem a bryndzou",
  "Zapečené špagety",
  "Zapečené špecle",
  "Zapečený králík se žampiony a kukuřicí",
  "Zapečený květák se šunkou a sýrovou omáčkou",
  "Zapečený lilek s tomatovou omáčkou a sýrem ricotta",
  "Zapečený pangasius s brokolicí a jogurtovým přelivem",
  "Zapečený pangasius se sušenými rajčaty",
  "Zapečený pórek se žampiony",
  "Zapečený zeleninový nákyp s červenou čočkou",
  "Zapečený šmakoun se zeleninou a sýrem",
  "Zapékaná pohanka s kysaným zelím",
  "Zapékané brambory se šunkou",
  "Zapékaný kapustový nákyp",
  "Zapékaný květák se šunkou",
  "Zatočený králičí hřbet se zeleninou a brusinkami",
  "Zdravý karbenátek",
  "Zelenina s masem a vejcem",
  "Zelenina v hořčici",
  "Zeleninová caponata",
  "Zeleninová polévka",
  "Zeleninová polévka krémová",
  "Zeleninová polévka s cizrnou",
  "Zeleninová polévka s kapáním z tofu",
  "Zeleninová polévka s rybími knedlíčky",
  "Zeleninová polévka s pohankou",
  "Zeleninová polévka s pohankovými knedlíčky",
  "Zeleninová se sýrovým kapáním",
  "Zeleninová směs",
  "Zeleninová směs s vejci a sýrem",
  "Zeleninové bulgureto",
  "Zeleninové karbanátky",
  "Zeleninové karbanátky s ovesnými vločkami",
  "Zeleninové karbanátky s černou čočkou",
  "Zeleninové kari",
  "Zeleninové kostky",
  "Zeleninové krupeto se sýrem a brokolicí",
  "Zeleninové lečo se šunkou",
  "Zeleninové placičky",
  "Zeleninové placičky smažené",
  "Zeleninové ragú s červenou čočkou",
  "Zeleninové rizoto",
  "Zeleninové smaženky (řízky)",
  "Zeleninové suflé",
  "Zeleninové řízečky s jáhlovou moukou",
  "Zeleninové řízečky s pohankou",
  "Zeleninový boršč nezahuštěný",
  "Zeleninový košík",
  "Zeleninový krém",
  "Zeleninový kuskus se sójovými boby",
  "Zeleninový nákyp",
  "Zeleninový salát",
  "Zeleninový talíř",
  "Zeleninový talíř",
  "Zeleninový talíř",
  "Zeleninový řízek",
  "Zeleninový špíz",
  "Zelené fazolky",
  "Zelná polévka se šunkou",
  "Zelná taštička z listového těsta",
  "Zelné karbanátky i.",
  "Zelný s koprem",
  "Zelný salát",
  "Zelný salát s jablky a hroznovým vínem",
  "Zelný salát s kukuřicí",
  "Zelný závitek na rajčatech",
  "Zelová valašská polévka",
  "Zelí hlávkové dušené",
  "Zelí kysané",
  "Zelí plněné masem",
  "Zelí z cukety",
  "Zelí z dýně",
  "Zelňačka s fazolemi a rýží",
  "Zimní cizrnový salát s medovou řepou",
  "Zkušební pro radku",
  "Znojemský guláš",
  "Záhorácký závitek",
  "Základní rybí vývar",
  "Závin z listového těsta se špenátem a čedarem",
  "Závitek z rybího filetu",
  "Závitky se šunkou a sýrem",
  "Čaj",
  "Černá čočka s bramborami a kari kořením",
  "Červená čočka",
  "Česneková polévka",
  "Čevabčiči",
  "Čokoládový krém",
  "Čočka",
  "Čočkovo-cizrnový salát",
  "Čočková polévka",
  "Čočkové karbanátky",
  "Čočkové ragú se špagetami a parmazánem",
  "Čočkový dhál",
  "Čočkový eintopf",
  "Čočkový hamburger",
  "Čočkový kotlík",
  "Čočkový prejt",
  "Čočkový salát",
  "Čínská kuřecí směs",
  "Čínské zelí plněné kuřecí fašírkou s krupkami",
  "Řecká sýrová pomazánka",
  "Řecké kuřecí stehýnko",
  "Řecký guláš",
  "Řecký kuřecí špíz (souvlaky)",
  "Řecký salát",
  "Ředkvičkový salát",
  "Řez z kuřecí roládky se žampionovým ragú",
  "Římské těstoviny",
  "Římský lívaneček s tvarohovým krémem a jahodami",
  "Řízek „naruby“",
  "Řízečky",
  "Široké nudle s růžičkovou kapustou",
  "Šišky",
  "Škubánky opečené",
  "Škubánky opečené s mákem",
  "Šlehaný jogurt",
  "Šlehaný tvaroh",
  "Šlehaný tvaroh",
  "Šmakoun pod cibulovou krustou se špeclemi",
  "Šneci z kuřecího masa",
  "Šneci z tilápie",
  "Šopský salát",
  "Šopský salát (bulharský)",
  "Šoulet",
  "Špagetové placky s vejci a kukuřičným dipem",
  "Špagety",
  "Špaldové kynuté knedlíky",
  "Špaldové lívance s horkým ovocem a tvarohem",
  "Špaldové rizoto se žampióny",
  "Špaldový koláč s borůvkovým tvarohem",
  "Španělská rybí polévka",
  "Španělský ptáček",
  "Špecle s krůtím masem a petrželkou",
  "Špekové knedlíky",
  "Špekové koule",
  "Špenát dušený",
  "Špenátová bramborová kaše",
  "Špenátová omáčka",
  "Špenátová palačinka sypaná sýrem",
  "Špenátová polévka",
  "Špenátové flíčky",
  "Špenátové karbanátky",
  "Špenátové knedlíky",
  "Špenátové lasagne",
  "Špenátové noky",
  "Špenátové rizoto s vlašskými ořechy",
  "Špíz s houbami a cuketou",
  "Špíz z tofu a zeleniny se sugem",
  "Špíz ze šmakouna a žampionů",
  "Štikozubec s bylinkovou krustou",
  "Štikozubec s limetovou omáčkou",
  "Štikozubec zapečený s hlívou ústřičnou",
  "Štikozubec zapečený s rajčaty a bramborami",
  "Šumavské bifteky",
  "Šumavské knedlíky s kořenovou zeleninou",
  "Šumavské nudle",
  "Šumavské nudle zapečené se žampiony",
  "Šunková pěna",
  "Šunkové halušky",
  "Švédská roštěná",
  "Švédská rybí polévka",
  "Švédský lososový nákyp",
  "Švýcarský sýrový salát",
  "Šťouchané brambory",
  "Šťouchané brambory a restovaný hrášek",
  "Šťouchané brambory s cibulkou a petrželkou",
  "Šťouchané brambory s pohankou",
  "Šťouchané brambory, zelené fazolky",
  "Žampionové ragú se špeclemi",
  "Žampionové špagety",
  "Žampionový salát s fazolemi a těstovinou",
  "Žampiony na smetaně",
  "Žampiony plněné vaječnou směsí a sýrem",
  "Žampiónová omáčka jemná",
  "Žebírko zapečené v bramborách",
  "Žemlovka",
];

export const filtrMenu = [
  {
    title: "Obecné",
    name: "obecne",
    backend: "Obecne",
    options: [
      {
        title: "Vše",
        name: "vse",
        backend: "",
        checked: false,
      },
      {
        title: "Moje oblíbené",
        name: "moje",
        backend: "Oblíbené",
        checked: false,
      },
      {
        title: "Nutričně ověřeno",
        name: "nutricni",
        backend: "SchvalenoNT",
        checked: false,
      },
      {
        title: "Stáhnout do skladu",
        name: "sklad",
        backend: "MSklad",
        checked: false,
      },
      {
        title: "Videoreceptury",
        name: "videoreceptury",
        backend: "Video",
        checked: false,
      },
    ],
  },
  {
    title: "Speciální strava",
    name: "special",
    backend: "Dieta",
    options: [
      {
        title: "Bezlepková",
        name: "bezlepkova",
        backend: "Dieta1",
        checked: false,
      },
      {
        title: "Bezmléčná",
        name: "bezmlecna",
        backend: "Dieta2",
        checked: false,
      },
      {
        title: "Šetřící",
        name: "setrici",
        backend: "Dieta3",
        checked: false,
      },
    ],
  },
  {
    title: "Způsob přípravy",
    name: "priprava",
    backend: "TepelnaUprava",
    options: [
      {
        title: "Vařené",
        name: "varene",
        backend: "Vařené",
        checked: false,
      },
      {
        title: "Dušené",
        name: "dusene",
        backend: "Dušené",
        checked: false,
      },
      {
        title: "Pečené",
        name: "pecene",
        backend: "Pečené",
        checked: false,
      },
      {
        title: "Zapečené",
        name: "zapecene",
        backend: "Zapečené",
        checked: false,
      },
      {
        title: "Smažené",
        name: "smazene",
        backend: "Smažené",
        checked: false,
      },
      {
        title: "Ostatní",
        name: "ostatni",
        backend: "Ostatní",
        checked: false,
      },
    ],
  },
  {
    title: "Partner",
    name: "partner",
    backend: "Receptar",
    options: [
      {
        title: "Bidfood",
        name: "bidfood",
        backend: "20",
        checked: false,
      },
      {
        title: "Bonduelle",
        name: "bonduelle",
        backend: "21",
        checked: false,
      },
    ],
  },
];

export const groupsData = [
  {
    value: "nezadano",
    title: "Vše",
    options: [{ value: "vse", title: "Vše" }],
  },
  {
    value: "bezmase_sladke",
    title: "Bezmasé sladké pokrmy",
    options: [
      { value: "vse", title: "Vše" },
      { value: "pecene", title: "Pečené a smažené" },
      { value: "varene", title: "Vařené" },
      { value: "kase", title: "Kaše" },
    ],
  },
  {
    value: "bezmase_slane",
    title: "Bezmasé slané pokrmy",
    options: [
      { value: "vse", title: "Vše" },
      {
        value: "zeleninove",
        title: "Zeleninové",
      },
      {
        value: "lusteniny",
        title: "Luštěninové",
      },
      {
        value: "moucne",
        title: "Moučné a obilninové",
      },
      { value: "testovinove", title: "Těstovinové" },
      { value: "bramborove", title: "Bramborové" },
      { value: "houbove", title: "Houbové" },
      { value: "salaty", title: "Saláty" },
      { value: "ostatni", title: "Ostatní" },
    ],
  },
  {
    value: "doplnky",
    title: "Doplňky",
    options: [
      { value: "vse", title: "Vše" },
      {
        value: "salaty_zeleninove",
        title: "Saláty zeleninové",
      },
      {
        value: "salaty_ovocne",
        title: "Saláty ovocné",
      },
      {
        value: "kompoty",
        title: "Kompoty",
      },
      {
        value: "moucniky",
        title: "Moučníky",
      },
      {
        value: "mlecne_dezerty",
        title: "Mléčné dezerty",
      },
      {
        value: "zelenina_cerstva",
        title: "Zelenina čerstvá",
      },
      {
        value: "ovoce_cerstve",
        title: "Ovoce čerstvé",
      },
      {
        value: "ostatni",
        title: "Ostatní",
      },
    ],
  },
  {
    value: "masite",
    title: "Masité pokrmy",
    options: [
      { value: "vse", title: "Vše" },
      { value: "veprove", title: "Vepřové" },
      { value: "kureci", title: "Kuřecí" },
      { value: "kruti", title: "Krůtí" },
      { value: "kralici", title: "Králičí" },
      { value: "hovezi", title: "Hovězí" },
      { value: "zverina", title: "Zvěřina" },
      { value: "teleci", title: "Telecí" },
      { value: "vnitrnosti", title: "Vnitřnosti" },
      { value: "husi_a_kachni", title: "Husí a kachní" },
      { value: "ostatni", title: "Ostatní" },
      {
        value: "mleta_masa_a_masove_smesi",
        title: "Mletá masa a masové směsi",
      },
    ],
  },
  {
    value: "napoje",
    title: "Nápoje",
    options: [{ value: "vse", title: "Vše" }],
  },
  {
    value: "polevky",
    title: "Polévky",
    options: [
      { value: "vse", title: "Vše" },
      {
        value: "zeleninove",
        title: "Zeleninové",
      },
      {
        value: "lusteninove",
        title: "Luštěninové",
      },
      {
        value: "masove_a_rybi",
        title: "Masové a rybí",
      },
      {
        value: "obilninove",
        title: "Obilninové",
      },
      { value: "bramborove", title: "Bramborové" },
      { value: "vyvary", title: "Vývary" },
      { value: "houbove", title: "Houbové" },
      {
        value: "ostatni",
        title: "Ostatní",
      },
    ],
  },
  {
    value: "prilohy_a_prikrmy",
    title: "Přílohy a příkrmy",
    options: [
      { value: "vse", title: "Vše" },
      { value: "bramborove", title: "Bramborové" },
      { value: "testovinove", title: "Těstovinové" },
      { value: "obilninove", title: "Obilninové" },
      { value: "knedliky", title: "Knedlíky" },
      { value: "zelenina", title: "Zelenina" },
      { value: "omacky", title: "Omáčky" },
      { value: "pecivo", title: "Pečivo" },
      { value: "ostatni", title: "Ostatní" },
      { value: "lusteninove", title: "Luštěninové" },
    ],
  },
  {
    value: "rybi_pokrmy",
    title: "Rybí pokrmy",
    options: [{ value: "vse", title: "Vše" }],
  },
  {
    value: "svaciny",
    title: "Svačiny",
    options: [
      { value: "vse", title: "Vše" },
      {
        value: "pomazanky_syrove_a_tvarohove",
        title: "Pomazánky sýrové a tvarohové",
      },
      {
        value: "pomazanky_masove",
        title: "Pomazánky masové",
      },
      {
        value: "pomazanky_vajecne",
        title: "Pomazánky vaječné",
      },
      {
        value: "pomazanky_rybi",
        title: "Pomazánky rybí",
      },
      {
        value: "mlecne_vyrobky",
        title: "Mléčné výrobky",
      },
      {
        value: "kase",
        title: "Kaše",
      },
      {
        value: "pecivo",
        title: "Pečivo",
      },
      {
        value: "moucniky",
        title: "Moučníky",
      },
      {
        value: "ostatni",
        title: "Ostatní",
      },
      {
        value: "pomazanky_zeleninove/ovocne",
        title: "Pomazánky zeleninové/ovocné",
      },
      {
        value: "pomazanky_lusteninove",
        title: "Pomazánky luštěninové",
      },
      {
        value: "pomazanky_ostatni",
        title: "Pomazánky ostatní",
      },
    ],
  },
  {
    value: "zavarky",
    title: "Zavářky",
    options: [{ value: "vse", title: "Vše" }],
  },
];
